name: release

# run only on tags
on:
  push:
    tags:
      - 'v*'

permissions:
    id-token: write # needed for federation
    contents: write # needed to write releases

jobs:
  release:
    if: github.ref_type == 'tag' 
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        with:
          go-version: go.mod
          cache: true
      - uses: goto-bus-stop/setup-zig@7ab2955eb728f5440978d5824358023be3a2802d
      - name: Set output
        id: macos_sdk
        run: echo "path=$(xcrun --show-sdk-path)" >> $GITHUB_OUTPUT
      - uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SDK_PATH: ${{ steps.macos_sdk.outputs.path }}
          VERSION: ${{ github.ref_name }}
